version: "3"

services:
  app:
    container_name: tutorial-app
    build:
      context: ./build/app
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/dip-dev/go-tutorial
  mock-api:
    container_name: mock-server
    build:
      context: ./mock
    ports:
      - "8081:80"